name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Default configuratin (PHP 8.2, MongoDB 5.0, Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        ini-values: date.timezone=Europe/Berlin

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: >
        curl -sSL https://baltocdn.com/xp-framework/xp-runners/distribution/downloads/e/entrypoint/xp-run-8.6.2.sh > xp-run &&
        composer install --prefer-dist --no-scripts &&
        echo "vendor/autoload.php" > composer.pth

    - name: Run tests
      run: >
        docker run --name mongo --rm -p 27017:27017 -d mongo:5 && docker inspect mongo &&
        sh xp-run xp.unittest.TestRunner src/it/php -a mongodb://[::1]:27017 ;
        docker logs mongo ; docker stop mongo
