name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Default configuratin (PHP 8.3, MongoDB 5.0, Ubuntu)
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5
        ports:
          - 27017/tcp
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        ini-values: date.timezone=Europe/Berlin

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: >
        curl -sSL https://baltocdn.com/xp-framework/xp-runners/distribution/downloads/e/entrypoint/xp-run-8.8.0.sh > xp-run &&
        composer install --prefer-dist --no-scripts &&
        echo "vendor/autoload.php" > composer.pth

    - name: Bundle assets
      run: sh xp-run xp.frontend.BundleRunner -m src/main/webapp/assets/manifest.json src/main/webapp/assets

    - name: Run tests
      run: sh xp-run xp.test.Runner src/it/php --dsn=mongodb://localhost:${{ job.services.mongodb.ports[27017] }}
