name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: gd
        ini-values: date.timezone=Europe/Berlin

    - name: Install dependencies
      run: >
        curl -sSL https://github.com/xp-runners/reference/releases/download/v9.2.0/xp-run-9.2.0.sh > xp-run &&
        composer install --prefer-dist --no-scripts &&
        echo "vendor/autoload.php" > composer.pth

    - name: Bundle assets
      run: sh xp-run xp.frontend.BundleRunner -m src/main/webapp/assets/manifest.json src/main/webapp/assets

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: thekid/dialog:latest